language: go
sudo: false

matrix:
  include:
    - go: 1.2
    - go: 1.3
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: tip


before_install:
  - go get -t -v ./...

install:
  - # Skip

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
